window.teamMembers = {
  current: [
    {
      name: "苏婷",
      photo: "./assets/team/su-ting.jpg?v=20260612opt",
      level: "21级硕博研究生",
      degree: "doctoral",
      research: "二维材料的原位力学研究",
      interests: "瑜伽、旅游",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "万拾佳",
      photo: "./assets/team/wan-yijia.jpg?v=20260612opt",
      level: "22级硕博研究生",
      degree: "doctoral",
      research: "微纳米金属强度力学实验与晶体塑性仿真",
      interests: "游戏、阅读",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "余天昊",
      photo: "./assets/team/yu-tianhao.jpg?v=20260612opt",
      level: "24级博士研究生",
      degree: "doctoral",
      research: "高分子功能凝胶材料构筑与多尺度多场耦合机制研究",
      interests: "音乐、电子产品、电影",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "张子勤",
      photo: "./assets/team/zhang-ziqin.jpg?v=20260612opt",
      level: "24级硕博研究生",
      degree: "doctoral",
      research: "二维材料的原位力学研究",
      interests: "跳舞、运动",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "尚岩松",
      photo: "./assets/team/shang-yansong.jpg?v=20260612opt",
      level: "25级硕博研究生",
      degree: "doctoral",
      research: "金属氢损伤",
      interests: "健身、跳舞",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "黄智超",
      photo: "./assets/team/huang-zhichao.jpg?v=20260612opt",
      level: "24级硕士研究生",
      degree: "master",
      research: "高铁转向架耐候钢疲劳损伤失效研究",
      interests: "健身、跑步、音乐",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "宋家昌",
      photo: "./assets/team/song-jiachang.jpg?v=20260612opt",
      level: "24级硕士研究生",
      degree: "master",
      research: "第一性原理计算、电催化",
      interests: "游戏、看剧",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "徐嘉怡",
      photo: "./assets/team/xu-jiayi.jpg?v=20260612opt",
      level: "25级硕士研究生",
      degree: "master",
      research: "第一性原理计算",
      interests: "游戏、羽毛球",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "李博通",
      photo: "./assets/team/li-botong.jpg?v=20260612opt",
      level: "25级硕士研究生",
      degree: "master",
      research: "晶体塑性有限元仿真",
      interests: "游戏、电影",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "陈汉",
      level: "25级硕士研究生",
      degree: "master",
      research: "晶体塑性有限元仿真",
      interests: "阅读、音乐",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "汪增辉",
      photo: "./assets/team/wang-zenghui.jpg?v=20260612opt",
      level: "25级硕士研究生",
      degree: "master",
      research: "固态电池的锂枝晶失效模式",
      interests: "健身、游泳、游戏",
      destination: "在读",
      contact: "Available by request",
    },
    {
      name: "周一峰",
      photo: "./assets/team/zhou-yifeng.jpg?v=20260614",
      level: "25级硕士研究生",
      degree: "master",
      research: "结构疲劳与寿命预测",
      interests: "音乐、游泳、游戏",
      destination: "在读",
      contact: "Available by request",
    },
  ],
  alumni: [
    {
      name: "王祎珩",
      photo: "./assets/team/wang-yiheng.jpg?v=20260612opt",
      level: "23级硕士研究生",
      research: "微尺度金属疲劳损伤",
      interests: "骑行、电影、动漫",
      destination: "ABB（上海）机器人有限公司",
      contact: "Available by request",
    },
    {
      name: "吴昊",
      photo: "./assets/team/wu-hao.jpg?v=20260612opt",
      level: "23级硕士研究生",
      research: "第一性原理计算：铁电材料",
      interests: "电影、徒步、音乐",
      destination: "三一重工",
      contact: "Available by request",
    },
    {
      name: "董亚辉",
      photo: "./assets/team/dong-yahui.jpg?v=20260612opt",
      level: "23级硕士研究生",
      research: "微纳米合金强度及微组织影响晶体塑性仿真",
      interests: "音乐、电影、游戏",
      destination: "杭州天智精密科技有限公司",
      contact: "Available by request",
    },
    {
      name: "徐渝京",
      photo: "./assets/team/xu-yujing.jpg?v=20260612opt",
      level: "23级硕士研究生",
      research: "第一性原理、电催化",
      interests: "游戏、跳舞",
      destination: "长江电力有限公司",
      contact: "Available by request",
    },
    {
      name: "史春浩",
      photo: "./assets/team/shi-chunhao.jpg?v=20260612shi",
      level: "23级硕士研究生",
      research: "柔性薄膜太阳电池、机械结构强度",
      interests: "游戏、阅读、电影",
      destination: "格科半导体有限公司",
      contact: "Available by request",
    },
    {
      name: "张文雨",
      level: "21级硕士研究生",
      research: "",
      interests: "游戏、健身",
      destination: "中芯国际集成电路制造（北京）有限公司",
      contact: "Available by request",
    },
    {
      name: "王春雨",
      level: "21级硕士研究生",
      research: "形状记忆合金弹卡性能研究、高通量相场模拟",
      interests: "网球、旅游",
      destination: "上海交通大学深造",
      contact: "Available by request",
    },
    {
      name: "韩忠",
      level: "21级硕士研究生",
      research: "断裂相场",
      interests: "游戏、旅游",
      destination: "远景动力技术（江苏）有限公司",
      contact: "Available by request",
    },
    {
      name: "惠云龙",
      level: "22级硕士研究生",
      research: "冲击动力学",
      interests: "绘画",
      destination: "中国电子科技集团公司第三十九研究所",
      contact: "Available by request",
    },
    {
      name: "俞添琛",
      level: "22级硕士研究生",
      research: "",
      interests: "篮球、健身、网球",
      destination: "中国船舶集团上海船舶研究设计院",
      contact: "Available by request",
    },
    {
      name: "李林峰",
      level: "22级硕士研究生",
      research: "第一性原理、电催化",
      interests: "打游戏",
      destination: "内德史罗夫有限公司",
      contact: "Available by request",
    },
    {
      name: "吴广泽",
      level: "22级硕士研究生",
      research: "",
      interests: "游戏",
      destination: "远景能源有限公司",
      contact: "Available by request",
    },
    {
      name: "曾凡明",
      level: "20级硕士研究生",
      research: "",
      interests: "爬山、音乐",
      destination: "浙江华云科技有限公司",
      contact: "Available by request",
    },
    {
      name: "程华兴",
      level: "20级硕士研究生",
      research: "高温蠕变",
      interests: "劳逸逸结合",
      destination: "联合汽车电子有限公司",
      contact: "Available by request",
    },
    {
      name: "杨锐",
      level: "20级硕士研究生",
      research: "",
      interests: "篮球",
      destination: "湖北武汉选调生",
      contact: "Available by request",
    },
    {
      name: "李振凯",
      level: "20级硕士研究生",
      research: "",
      interests: "",
      destination: "南京航空航天大学读博",
      contact: "Available by request",
    },
    {
      name: "陈亦楠",
      level: "20级硕士研究生",
      research: "",
      interests: "网球、旅游、阅读",
      destination: "纳铁福传动系统",
      contact: "Available by request",
    },
    {
      name: "金徐洁",
      level: "20级硕士研究生",
      research: "",
      interests: "看剧、追星、旅游",
      destination: "上海联影医疗",
      contact: "Available by request",
    },
    {
      name: "许国庆",
      level: "20级硕士研究生",
      research: "",
      interests: "",
      destination: "上海凯赛生物技术股份有限公司",
      contact: "Available by request",
    },
    {
      name: "陈豪",
      level: "19级硕士研究生",
      research: "第一性原理计算、析氢催化",
      interests: "游戏、旅游",
      destination: "上海集成电路研发中心",
      contact: "Available by request",
    },
    {
      name: "周夺",
      level: "19级硕士研究生",
      research: "结构疲劳仿真",
      interests: "羽毛球、音乐",
      destination: "先导慧电",
      contact: "Available by request",
    },
    {
      name: "向名芝",
      level: "19级硕士研究生",
      research: "",
      interests: "",
      destination: "",
      contact: "Available by request",
    },
    {
      name: "李晟",
      level: "19级硕士研究生",
      research: "微纳材料的力学性能分析",
      interests: "骑行、旅游、桌游、游戏",
      destination: "浦东新区公务员选调生",
      contact: "Available by request",
    },
    {
      name: "尹朦",
      level: "16级本科生",
      research: "第一性原理计算、有限元仿真",
      interests: "旅游、猫",
      destination: "日本东北大学",
      contact: "Available by request",
    },
  ],
};
